"""Added new models for teklif, servis, alacak_borc, gelir_gider, and musteri

Revision ID: 9e333a59b42a
Revises: ce81fade7327
Create Date: 2024-11-11 14:30:12.163534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e333a59b42a'
down_revision = 'ce81fade7327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gelir_gider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alacak_borc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('tur', sa.String(length=20), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servisler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('yapilan_is', sa.String(length=200), nullable=False),
    sa.Column('ucret', sa.Float(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teklifler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('toplam_fiyat', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teklifler')
    op.drop_table('servisler')
    op.drop_table('alacak_borc')
    op.drop_table('musteriler')
    op.drop_table('gelir_gider')
    # ### end Alembic commands ###
